services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=demo
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
